/**
 * Claims Feature - Mock Data
 * ---------------------------------------
 * Mock data for claims feature during development.
 * 
 * Usage:
 * - Used when NEXT_PUBLIC_USE_MOCK=true
 * - Replace with real API calls in claims.api.ts
 * 
 * Removal Instructions:
 * - Set NEXT_PUBLIC_USE_MOCK=false in .env.local
 * - This file can be deleted once backend is integrated
 * 
 * @module features/claims/claims.mock
 */

import { Claim } from "./claims.types";

/**
 * Mock claims list for development
 */
export const MOCK_CLAIMS: Claim[] = [
  {
    id: "1",
    claimNumber: "CLM-2026-001",
    type: "medical",
    status: "approved",
    submittedDate: "2026-02-02",
    serviceDate: "2026-02-01",
    providerName: "City Medical Center",
    providerNPI: "1234567890",
    diagnosis: "Annual Physical Exam",
    diagnosisCode: "Z00.00",
    amountBilled: 250,
    amountCovered: 200,
    amountPaid: 0,
    patientResponsibility: 50,
    description: "Annual checkup including blood work and physical examination",
    attachments: [
      {
        id: "1",
        fileName: "medical-receipt.pdf",
        fileUrl: "#",
        fileType: "application/pdf",
        fileSize: 245000,
        uploadedAt: "2026-02-02",
      },
    ],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-02T10:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received and logged claim submission",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-03T14:30:00Z",
        description: "Claim is being reviewed by our team",
        team: "Medical Review Team",
        handlerName: "Denil",
        action: "Reviewing claim details and medical records",
      },
      {
        id: "3",
        status: "approved",
        date: "2026-02-05T16:45:00Z",
        description: "Claim approved for payment",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Claim verified and approved for payment processing",
      },
      {
        id: "4",
        status: "paid",
        date: "2026-02-07T09:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $200.00 processed to provider",
      },
    ],
    createdAt: "2026-02-02",
    updatedAt: "2026-02-07",
  },
  {
    id: "2",
    claimNumber: "CLM-2026-002",
    type: "dental",
    status: "under_review",
    submittedDate: "2026-02-12",
    serviceDate: "2026-02-10",
    providerName: "Bright Smiles Dental",
    diagnosis: "Dental Cleaning",
    amountBilled: 150,
    amountCovered: 120,
    amountPaid: 0,
    patientResponsibility: 30,
    description: "Routine dental cleaning",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-12T09:30:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received dental claim submission",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-13T11:00:00Z",
        description: "Under review by dental claims team",
        team: "Dental Review Team",
        handlerName: "Nasib",
        action: "Pending: Reviewing dental procedure codes and coverage eligibility",
      },
    ],
    createdAt: "2026-02-12",
    updatedAt: "2026-02-13",
  },
  {
    id: "3",
    claimNumber: "CLM-2026-003",
    type: "prescription",
    status: "paid",
    submittedDate: "2026-02-05",
    serviceDate: "2026-02-05",
    providerName: "HealthPlus Pharmacy",
    diagnosis: "Prescription Medication",
    amountBilled: 85,
    amountCovered: 65,
    amountPaid: 65,
    patientResponsibility: 20,
    description: "Monthly prescription refill",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-05T08:15:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received prescription claim submission",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-05T14:20:00Z",
        description: "Claim is being reviewed by our team",
        team: "Pharmacy Review Team",
        handlerName: "Thara",
        action: "Verified prescription details and pharmacy eligibility",
      },
      {
        id: "3",
        status: "approved",
        date: "2026-02-05T17:30:00Z",
        description: "Claim approved for payment",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Prescription claim approved for payment",
      },
      {
        id: "4",
        status: "paid",
        date: "2026-02-06T09:10:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $65.00 processed to pharmacy",
      },
    ],
    createdAt: "2026-02-05",
    updatedAt: "2026-02-06",
  },
  {
    id: "4",
    claimNumber: "CLM-2026-004",
    type: "vision",
    status: "rejected",
    submittedDate: "2026-01-30",
    serviceDate: "2026-01-28",
    providerName: "Vision Plus",
    providerNPI: "1234567890",
    diagnosis: "Eye Exam",
    diagnosisCode: "Z01.00",
    amountBilled: 1200,
    amountCovered: 0,
    amountPaid: 0,
    patientResponsibility: 1200,
    description: "Annual eye exam",
    attachments: [
      {
        id: "1",
        fileName: "vision-receipt.pdf",
        fileUrl: "#",
        fileType: "application/pdf",
        fileSize: 245000,
        uploadedAt: "2026-01-30",
      },
    ],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-30T10:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received vision claim submission",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-01-31T14:30:00Z",
        description: "Claim is being reviewed by our team",
        team: "Vision Review Team",
        handlerName: "Nasib",
        action: "Reviewing claim documentation",
      },
      {
        id: "3",
        status: "rejected",
        date: "2026-02-01T11:00:00Z",
        description: "Claim rejected due to missing documentation",
        team: "Vision Review Team",
        handlerName: "Nasib",
        action: "Rejected: Missing itemized receipt and provider notes",
      },
      {
        id: "4",
        status: "resubmitted",
        date: "2026-02-03T09:15:00Z",
        description: "Claim resubmitted with missing documents",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received resubmission with additional documents",
      },
      {
        id: "5",
        status: "approved",
        date: "2026-02-05T16:20:00Z",
        description: "Claim approved after review",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Claim verified and approved after document review",
      },
    ],
    createdAt: "2026-01-30",
    updatedAt: "2026-02-05",
  },
  {
    id: "5",
    claimNumber: "CLM-2026-005",
    type: "medical",
    status: "submitted",
    submittedDate: "2026-02-15",
    serviceDate: "2026-02-14",
    providerName: "Central Hospital",
    providerNPI: "1987654321",
    diagnosis: "Urgent Care Visit",
    diagnosisCode: "R50.9",
    amountBilled: 320,
    amountCovered: 320,
    amountPaid: 0,
    patientResponsibility: 0,
    description: "Urgent care visit for fever - Full coverage",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-15T11:30:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received urgent care claim submission",
      },
    ],
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
  },
  {
    id: "6",
    claimNumber: "CLM-2026-006",
    type: "dental",
    status: "submitted",
    submittedDate: "2026-02-16",
    serviceDate: "2026-02-15",
    providerName: "Premier Dental Group",
    diagnosis: "Root Canal Treatment",
    amountBilled: 1500,
    amountCovered: 1500,
    amountPaid: 0,
    patientResponsibility: 0,
    description: "Emergency root canal - Full coverage approved",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-16T09:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received emergency dental claim",
      },
    ],
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
  {
    id: "7",
    claimNumber: "CLM-2026-007",
    type: "prescription",
    status: "submitted",
    submittedDate: "2026-02-14",
    serviceDate: "2026-02-14",
    providerName: "CVS Pharmacy",
    diagnosis: "Medication Refill",
    amountBilled: 215,
    amountCovered: 180,
    amountPaid: 0,
    patientResponsibility: 35,
    description: "Diabetes medication refill",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-14T14:45:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received prescription claim submission",
      },
    ],
    createdAt: "2026-02-14",
    updatedAt: "2026-02-14",
  },
  {
    id: "8",
    claimNumber: "CLM-2026-008",
    type: "medical",
    status: "under_review",
    submittedDate: "2026-02-11",
    serviceDate: "2026-02-10",
    providerName: "Regional Medical Center",
    diagnosis: "Lab Work and Blood Tests",
    amountBilled: 450,
    amountCovered: 450,
    amountPaid: 0,
    patientResponsibility: 0,
    description: "Comprehensive blood panel - Full coverage",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-11T10:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received lab work claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-13T13:20:00Z",
        description: "Claim is being reviewed by our team",
        team: "Lab Review Team",
        handlerName: "Denil",
        action: "Pending: Verifying lab codes and coverage",
      },
    ],
    createdAt: "2026-02-11",
    updatedAt: "2026-02-13",
  },
  {
    id: "9",
    claimNumber: "CLM-2026-009",
    type: "vision",
    status: "approved",
    submittedDate: "2026-02-08",
    serviceDate: "2026-02-07",
    providerName: "EyeCare Associates",
    diagnosis: "Contact Lens Fitting",
    amountBilled: 280,
    amountCovered: 280,
    amountPaid: 0,
    patientResponsibility: 0,
    description: "Contact lens fitting and adjustment - Full coverage",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-08T10:30:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received contact lens claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-09T11:15:00Z",
        description: "Claim is being reviewed",
        team: "Vision Review Team",
        handlerName: "Nasib",
        action: "Approved: Contact lens services covered",
      },
      {
        id: "3",
        status: "approved",
        date: "2026-02-10T14:00:00Z",
        description: "Claim approved for payment",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Approved for immediate payment processing",
      },
    ],
    createdAt: "2026-02-08",
    updatedAt: "2026-02-10",
  },
  {
    id: "10",
    claimNumber: "CLM-2026-010",
    type: "hospitalization",
    status: "submitted",
    submittedDate: "2026-02-13",
    serviceDate: "2026-02-12",
    providerName: "City General Hospital",
    diagnosis: "Overnight Hospital Stay",
    amountBilled: 5000,
    amountCovered: 5000,
    amountPaid: 0,
    patientResponsibility: 0,
    description: "Emergency hospital admission - Full coverage",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-13T15:45:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received hospitalization claim",
      },
    ],
    createdAt: "2026-02-13",
    updatedAt: "2026-02-13",
  },
  {
    id: "11",
    claimNumber: "CLM-2026-011",
    type: "medical",
    status: "paid",
    submittedDate: "2026-01-25",
    serviceDate: "2026-01-24",
    providerName: "Metro Clinic",
    providerNPI: "9876543210",
    diagnosis: "Follow-up Consultation",
    diagnosisCode: "Z09",
    amountBilled: 180,
    amountCovered: 150,
    amountPaid: 150,
    patientResponsibility: 30,
    description: "Post-surgery follow-up consultation",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-25T09:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received medical claim submission",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-01-26T10:30:00Z",
        description: "Claim under review",
        team: "Medical Review Team",
        handlerName: "Denil",
        action: "Reviewing medical records",
      },
      {
        id: "3",
        status: "approved",
        date: "2026-01-28T14:00:00Z",
        description: "Claim approved",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Approved for payment",
      },
      {
        id: "4",
        status: "paid",
        date: "2026-01-30T11:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $150.00 processed",
      },
    ],
    createdAt: "2026-01-25",
    updatedAt: "2026-01-30",
  },
  {
    id: "12",
    claimNumber: "CLM-2026-012",
    type: "prescription",
    status: "rejected",
    submittedDate: "2026-02-10",
    serviceDate: "2026-02-09",
    providerName: "QuickMeds Pharmacy",
    diagnosis: "Medication Refill",
    amountBilled: 95,
    amountCovered: 0,
    amountPaid: 0,
    patientResponsibility: 95,
    description: "Non-formulary medication not covered",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-10T08:30:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Denil",
        action: "Received prescription claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-10T13:00:00Z",
        description: "Under review",
        team: "Pharmacy Review Team",
        handlerName: "Thara",
        action: "Reviewing prescription coverage",
      },
      {
        id: "3",
        status: "rejected",
        date: "2026-02-11T09:00:00Z",
        description: "Claim rejected",
        team: "Pharmacy Review Team",
        handlerName: "Thara",
        action: "Rejected: Medication not on formulary list",
      },
    ],
    createdAt: "2026-02-10",
    updatedAt: "2026-02-11",
  },
  {
    id: "13",
    claimNumber: "CLM-2026-013",
    type: "dental",
    status: "rejected",
    submittedDate: "2026-02-08",
    serviceDate: "2026-02-07",
    providerName: "Smile Dental Care",
    diagnosis: "Cosmetic Procedure",
    amountBilled: 850,
    amountCovered: 0,
    amountPaid: 0,
    patientResponsibility: 850,
    description: "Teeth whitening - cosmetic not covered",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-08T10:15:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Synthia",
        action: "Received dental claim",
      },
      {
        id: "2",
        status: "rejected",
        date: "2026-02-09T11:00:00Z",
        description: "Claim rejected",
        team: "Dental Review Team",
        handlerName: "Nasib",
        action: "Rejected: Cosmetic procedures not covered under policy",
      },
    ],
    createdAt: "2026-02-08",
    updatedAt: "2026-02-09",
  },
  {
    id: "14",
    claimNumber: "CLM-2026-014",
    type: "medical",
    status: "paid",
    submittedDate: "2026-01-20",
    serviceDate: "2026-01-19",
    providerName: "Family Health Center",
    providerNPI: "5432167890",
    diagnosis: "Vaccination",
    diagnosisCode: "Z23",
    amountBilled: 75,
    amountCovered: 75,
    amountPaid: 75,
    patientResponsibility: 0,
    description: "Annual flu vaccination - fully covered",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-20T14:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received vaccination claim",
      },
      {
        id: "2",
        status: "approved",
        date: "2026-01-21T10:00:00Z",
        description: "Claim approved",
        team: "Medical Review Team",
        handlerName: "Denil",
        action: "Preventive care approved",
      },
      {
        id: "3",
        status: "paid",
        date: "2026-01-22T09:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $75.00 processed",
      },
    ],
    createdAt: "2026-01-20",
    updatedAt: "2026-01-22",
  },
  {
    id: "15",
    claimNumber: "CLM-2026-015",
    type: "vision",
    status: "rejected",
    submittedDate: "2026-02-06",
    serviceDate: "2026-02-05",
    providerName: "Clear Vision Optical",
    diagnosis: "Designer Frames",
    amountBilled: 450,
    amountCovered: 0,
    amountPaid: 0,
    patientResponsibility: 450,
    description: "Designer frames exceed coverage limit",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-06T11:30:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Dency",
        action: "Received vision claim",
      },
      {
        id: "2",
        status: "rejected",
        date: "2026-02-07T10:00:00Z",
        description: "Claim rejected",
        team: "Vision Review Team",
        handlerName: "Nasib",
        action: "Rejected: Frame cost exceeds $200 policy limit",
      },
    ],
    createdAt: "2026-02-06",
    updatedAt: "2026-02-07",
  },
  {
    id: "16",
    claimNumber: "CLM-2026-016",
    type: "medical",
    status: "submitted",
    submittedDate: "2026-02-16",
    serviceDate: "2026-02-15",
    providerName: "Downtown Medical Associates",
    providerNPI: "7654321098",
    diagnosis: "Chest X-Ray",
    diagnosisCode: "R07.9",
    amountBilled: 320,
    amountCovered: 280,
    amountPaid: 0,
    patientResponsibility: 40,
    description: "Diagnostic X-ray for chest pain evaluation",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-16T08:00:00Z",
        description: "Claim submitted for review",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received diagnostic imaging claim",
      },
    ],
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
  {
    id: "17",
    claimNumber: "CLM-2026-017",
    type: "prescription",
    status: "paid",
    submittedDate: "2026-01-18",
    serviceDate: "2026-01-18",
    providerName: "Wellness Pharmacy",
    diagnosis: "Blood Pressure Medication",
    amountBilled: 55,
    amountCovered: 50,
    amountPaid: 50,
    patientResponsibility: 5,
    description: "Monthly blood pressure medication refill",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-18T10:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Denil",
        action: "Received prescription claim",
      },
      {
        id: "2",
        status: "approved",
        date: "2026-01-18T15:00:00Z",
        description: "Auto-approved",
        team: "Pharmacy Review Team",
        handlerName: "Thara",
        action: "Approved automatically",
      },
      {
        id: "3",
        status: "paid",
        date: "2026-01-19T09:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $50.00 processed",
      },
    ],
    createdAt: "2026-01-18",
    updatedAt: "2026-01-19",
  },
  {
    id: "18",
    claimNumber: "CLM-2026-018",
    type: "dental",
    status: "under_review",
    submittedDate: "2026-02-15",
    serviceDate: "2026-02-14",
    providerName: "Advanced Dental Care",
    diagnosis: "Crown Replacement",
    amountBilled: 1800,
    amountCovered: 1200,
    amountPaid: 0,
    patientResponsibility: 600,
    description: "Porcelain crown replacement on molar",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-15T09:30:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Synthia",
        action: "Received crown replacement claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-15T14:00:00Z",
        description: "Under review",
        team: "Dental Review Team",
        handlerName: "Nasib",
        action: "Reviewing necessity and dental records",
      },
    ],
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
  },
  {
    id: "19",
    claimNumber: "CLM-2026-019",
    type: "medical",
    status: "paid",
    submittedDate: "2026-01-15",
    serviceDate: "2026-01-14",
    providerName: "Women's Health Clinic",
    providerNPI: "3456789012",
    diagnosis: "Preventive Care",
    diagnosisCode: "Z00.01",
    amountBilled: 220,
    amountCovered: 220,
    amountPaid: 220,
    patientResponsibility: 0,
    description: "Annual preventive health screening - fully covered",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-15T11:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received preventive care claim",
      },
      {
        id: "2",
        status: "approved",
        date: "2026-01-16T10:00:00Z",
        description: "Approved",
        team: "Medical Review Team",
        handlerName: "Denil",
        action: "Preventive care approved",
      },
      {
        id: "3",
        status: "paid",
        date: "2026-01-17T09:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $220.00 processed",
      },
    ],
    createdAt: "2026-01-15",
    updatedAt: "2026-01-17",
  },
  {
    id: "20",
    claimNumber: "CLM-2026-020",
    type: "vision",
    status: "submitted",
    submittedDate: "2026-02-16",
    serviceDate: "2026-02-16",
    providerName: "OptiCare Vision Center",
    diagnosis: "Eye Exam and Glasses",
    amountBilled: 350,
    amountCovered: 250,
    amountPaid: 0,
    patientResponsibility: 100,
    description: "Annual eye exam with new prescription glasses",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-16T13:30:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Thara",
        action: "Received vision claim",
      },
    ],
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
  {
    id: "21",
    claimNumber: "CLM-2026-021",
    type: "prescription",
    status: "rejected",
    submittedDate: "2026-02-09",
    serviceDate: "2026-02-09",
    providerName: "Express Pharmacy",
    diagnosis: "Weight Loss Medication",
    amountBilled: 280,
    amountCovered: 0,
    amountPaid: 0,
    patientResponsibility: 280,
    description: "Weight loss medication not covered",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-09T09:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Johncon",
        action: "Received prescription claim",
      },
      {
        id: "2",
        status: "rejected",
        date: "2026-02-10T11:00:00Z",
        description: "Claim rejected",
        team: "Pharmacy Review Team",
        handlerName: "Thara",
        action: "Rejected: Weight loss medications excluded from coverage",
      },
    ],
    createdAt: "2026-02-09",
    updatedAt: "2026-02-10",
  },
  {
    id: "22",
    claimNumber: "CLM-2026-022",
    type: "medical",
    status: "under_review",
    submittedDate: "2026-02-14",
    serviceDate: "2026-02-13",
    providerName: "Urgent Care Plus",
    providerNPI: "8901234567",
    diagnosis: "Minor Surgery",
    diagnosisCode: "L02.91",
    amountBilled: 950,
    amountCovered: 750,
    amountPaid: 0,
    patientResponsibility: 200,
    description: "Abscess drainage procedure",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-14T10:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Denil",
        action: "Received surgical procedure claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-02-14T16:00:00Z",
        description: "Under review",
        team: "Medical Review Team",
        handlerName: "Denil",
        action: "Reviewing procedure documentation",
      },
    ],
    createdAt: "2026-02-14",
    updatedAt: "2026-02-14",
  },
  {
    id: "23",
    claimNumber: "CLM-2026-023",
    type: "dental",
    status: "paid",
    submittedDate: "2026-01-12",
    serviceDate: "2026-01-11",
    providerName: "Family Dentistry",
    diagnosis: "Tooth Extraction",
    amountBilled: 320,
    amountCovered: 250,
    amountPaid: 250,
    patientResponsibility: 70,
    description: "Simple tooth extraction",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-01-12T09:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Synthia",
        action: "Received extraction claim",
      },
      {
        id: "2",
        status: "under_review",
        date: "2026-01-13T10:00:00Z",
        description: "Under review",
        team: "Dental Review Team",
        handlerName: "Nasib",
        action: "Reviewing dental records",
      },
      {
        id: "3",
        status: "approved",
        date: "2026-01-14T11:00:00Z",
        description: "Approved",
        team: "Approval Team",
        handlerName: "Synthia",
        action: "Approved for payment",
      },
      {
        id: "4",
        status: "paid",
        date: "2026-01-16T09:00:00Z",
        description: "Payment processed",
        team: "Finance Team",
        handlerName: "Dency",
        action: "Payment of $250.00 processed",
      },
    ],
    createdAt: "2026-01-12",
    updatedAt: "2026-01-16",
  },
  {
    id: "24",
    claimNumber: "CLM-2026-024",
    type: "medical",
    status: "submitted",
    submittedDate: "2026-02-15",
    serviceDate: "2026-02-14",
    providerName: "Sports Medicine Clinic",
    providerNPI: "4567890123",
    diagnosis: "Physical Therapy",
    diagnosisCode: "M25.561",
    amountBilled: 185,
    amountCovered: 150,
    amountPaid: 0,
    patientResponsibility: 35,
    description: "Physical therapy session for knee pain",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-15T15:00:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Dency",
        action: "Received physical therapy claim",
      },
    ],
    createdAt: "2026-02-15",
    updatedAt: "2026-02-15",
  },
  {
    id: "25",
    claimNumber: "CLM-2026-025",
    type: "prescription",
    status: "submitted",
    submittedDate: "2026-02-16",
    serviceDate: "2026-02-16",
    providerName: "MedMart Pharmacy",
    diagnosis: "Antibiotic Prescription",
    amountBilled: 42,
    amountCovered: 35,
    amountPaid: 0,
    patientResponsibility: 7,
    description: "Antibiotic for bacterial infection",
    attachments: [],
    timeline: [
      {
        id: "1",
        status: "submitted",
        date: "2026-02-16T16:45:00Z",
        description: "Claim submitted",
        team: "Claims Intake Team",
        handlerName: "Nasib",
        action: "Received prescription claim",
      },
    ],
    createdAt: "2026-02-16",
    updatedAt: "2026-02-16",
  },
];

/**
 * Mock claim detail with full timeline
 */
export const MOCK_CLAIM_DETAIL: Claim = MOCK_CLAIMS[0];

/**
 * Mock cases for claim workflow
 */
export const MOCK_CASES: Record<string, {
  caseNumber: string;
  reviewer: string;
  reason: string;
  lastUpdated: string;
  messages: Array<{
    id: string;
    author: string;
    message: string;
    date: string;
  }>;
}> = {
  "4": {
    caseNumber: "CASE-2026-1187",
    reviewer: "Synthia",
    reason: "Missing itemized receipt and provider notes. Please upload the missing documents and confirm service date.",
    lastUpdated: "2026-02-05",
    messages: [
      {
        id: "msg-1",
        author: "Claims Team",
        message: "We need the itemized receipt and provider notes to continue your claim.",
        date: "2026-02-01T11:05:00Z",
      },
      {
        id: "msg-2",
        author: "You",
        message: "Thanks, I will upload the missing documents today.",
        date: "2026-02-01T12:10:00Z",
      },
      {
        id: "msg-3",
        author: "Claims Team",
        message: "Documents received. Processing your claim now.",
        date: "2026-02-05T08:30:00Z",
      },
    ],
  },
  "12": {
    caseNumber: "CASE-2026-2105",
    reviewer: "Thara",
    reason: "Medication not on formulary list. Please contact your doctor for alternative medications covered under your plan.",
    lastUpdated: "2026-02-11",
    messages: [
      {
        id: "msg-1",
        author: "Claims Team",
        message: "This medication is not covered under your current plan. We recommend discussing alternatives with your provider.",
        date: "2026-02-11T09:05:00Z",
      },
    ],
  },
  "13": {
    caseNumber: "CASE-2026-2089",
    reviewer: "Nasib",
    reason: "Cosmetic procedures are not covered under your current policy. Only medically necessary dental treatments are eligible.",
    lastUpdated: "2026-02-09",
    messages: [
      {
        id: "msg-1",
        author: "Claims Team",
        message: "Cosmetic procedures like teeth whitening are excluded from coverage per your policy terms.",
        date: "2026-02-09T11:05:00Z",
      },
    ],
  },
  "15": {
    caseNumber: "CASE-2026-2067",
    reviewer: "Nasib",
    reason: "Frame cost exceeds the $200 policy limit. You may resubmit with frames within the coverage limit.",
    lastUpdated: "2026-02-07",
    messages: [
      {
        id: "msg-1",
        author: "Claims Team",
        message: "Your policy covers up to $200 for frames. The submitted frames exceed this limit by $250.",
        date: "2026-02-07T10:05:00Z",
      },
    ],
  },
  "21": {
    caseNumber: "CASE-2026-2122",
    reviewer: "Thara",
    reason: "Weight loss medications are excluded from coverage under your current policy. Only FDA-approved medications for chronic conditions are covered.",
    lastUpdated: "2026-02-10",
    messages: [
      {
        id: "msg-1",
        author: "Claims Team",
        message: "Weight loss medications are not covered under your policy terms. Please consult your provider for covered alternatives.",
        date: "2026-02-10T11:05:00Z",
      },
    ],
  },
};

/**
 * Get mock claim by ID
 */
export const getMockClaimById = (id: string): Claim | undefined => {
  return MOCK_CLAIMS.find((claim) => claim.id === id);
};

/**
 * Get mock case by claim ID
 */
export const getMockCaseByClaimId = (claimId: string) => {
  return MOCK_CASES[claimId];
};

/**
 * Withdraw a mock claim
 */
export const withdrawMockClaim = (id: string): Claim => {
  const claimIndex = MOCK_CLAIMS.findIndex((claim) => claim.id === id);
  if (claimIndex === -1) {
    throw new Error("Claim not found");
  }

  const existing = MOCK_CLAIMS[claimIndex];
  const now = new Date().toISOString();

  if (existing.status === "withdrawn") {
    return existing;
  }

  const updated: Claim = {
    ...existing,
    status: "withdrawn",
    updatedAt: now,
    timeline: [
      ...existing.timeline,
      {
        id: `tl-withdrawn-${Date.now()}`,
        status: "withdrawn",
        date: now,
        description: "Claim withdrawn by member",
      },
    ],
  };

  MOCK_CLAIMS[claimIndex] = updated;
  return updated;
};

/**
 * Resubmit a mock claim (moves to submitted status)
 */
export const resubmitMockClaim = (id: string): Claim => {
  const claimIndex = MOCK_CLAIMS.findIndex((claim) => claim.id === id);
  if (claimIndex === -1) {
    throw new Error("Claim not found");
  }

  const existing = MOCK_CLAIMS[claimIndex];
  const now = new Date().toISOString();

  const updated: Claim = {
    ...existing,
    status: "submitted",
    updatedAt: now,
    timeline: [
      ...existing.timeline,
      {
        id: `tl-resubmitted-${Date.now()}`,
        status: "resubmitted",
        date: now,
        description: "Claim resubmitted by member",
      },
      {
        id: `tl-submitted-${Date.now()}`,
        status: "submitted",
        date: now,
        description: "Claim submitted for review",
      },
    ],
  };

  MOCK_CLAIMS[claimIndex] = updated;
  return updated;
};
